multitenancy:   
  datasourceCache:
    maximumSize: 100
    expireAfterAccess: 1
  master:
    url: jdbc:mysql://localhost:3306/cda_master?autoReconnect=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: cda
    password:
    entityManager:
      packages: test
  tenant:
    host: localhost
    port: 3306
    connection:
      maximumPoolSize: 5
      minimumIdle: 0
      idleTimeout: 30000
encryption:
  secret: 9e9dbbb2-f4bc-11ed-a05b-0242ac120003
  salt: triforce

dbms:
  name: mariadb # Available options: (mariadb, mysql, postgres, oracle, sql_server)
