name: Build and Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.3
        env:
          MARIADB_ROOT_PASSWORD: 
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Wait for MariaDB to be ready
      run: |
        while ! mysqladmin ping -h 127.0.0.1 -P 3306 -u root --silent; do
          sleep 1
        done

    - name: Setup Database
      run: ./scripts/configdb

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
    
    - name: Build with Maven
      run: mvn clean install
    
    - name: Run tests with Maven
      run: mvn test
